name: Build images
on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:
    branches:
      - main

env:
  TAG_NAME: 3.1.3-alpine
  USER_NAME: gaizkaurd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build builder image
        working-directory: ./Builder
        run: docker build -t builder .

      - name: Build final image
        working-directory: ./Final
        run: docker build -t final .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Push the images to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |

          docker tag builder ghcr.io/${{ env.USER_NAME }}/rails-base-builder-3.1.2:latest
          docker tag builder ghcr.io/${{ env.USER_NAME }}/rails-base-builder-3.1.2:${{ env.TAG_NAME }}
          docker push ghcr.io/${{ env.USER_NAME }}/rails-base-builder-3.1.2:latest
          docker push ghcr.io/${{ env.USER_NAME }}/rails-base-builder-3.1.2:${{ env.TAG_NAME }}

          docker tag final ghcr.io/${{ env.USER_NAME }}/rails-base-final-3.1.2:latest
          docker push ghcr.io/${{ env.USER_NAME }}/rails-base-final-3.1.2:latest
          docker tag final ghcr.io/${{ env.USER_NAME }}/rails-base-final-3.1.2:${{ env.TAG_NAME }}
          docker push ghcr.io/${{ env.USER_NAME }}/rails-base-final-3.1.2:${{ env.TAG_NAME }}
